version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
      time: '13:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 0
    target-branch: main
    labels:
      - dependencies
      - release/dependencies
    versioning-strategy: increase-if-necessary
