version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 0
  target-branch: main
  labels:
  - dependencies
  - release/dependencies
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: marked
    versions:
    - "> 0.7.0"
