name: Push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: Codecademy/run-on-yarn@v2
        with:
          command: ${{ matrix.command }}

    strategy:
      fail-fast: false
      matrix:
        command: ['format:verify', 'lint', 'verify']

on: push
