name: Push

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn
      - run: yarn ${{ matrix.command }}

    strategy:
      fail-fast: false
      matrix:
        command: ['format:verify', 'lint', 'verify', 'syncpack:lint']
